stub out direnv with generic labels

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -22,13 +22,13 @@ fail() {
   exit 1
 }
 
-install_direnv() {
+install_SOMETHNG() {
   local install_type=$1
   local version=$2
   local install_path=$3
 
   if [ "$install_type" != "version" ]; then
-    fail "asdf-direnv supports release installs only"
+    fail "asdf-SOMETHING supports release installs only"
   fi
 
   local platform
@@ -46,14 +46,14 @@ install_direnv() {
     *) fail "Unsupported architecture" ;;
   esac
 
-  local download_url="https://github.com/direnv/direnv/releases/download/v${version}/direnv.${platform}-${architecture}"
-  local source_path="${install_path}/bin/direnv"
+  local download_url="https://github.com/ORG/REPO/releases/download/v${version}/${platform}-${architecture}"
+  local source_path="${install_path}/bin/SOMETHING"
 
   (
-    echo "∗ Downloading and installing direnv..."
+    echo "∗ Downloading and installing SOMETHING..."
     mkdir -p "${install_path}/bin"
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-    chmod +x "${install_path}/bin/direnv" || fail "Could not set executable bit on binary"
+    chmod +x "${install_path}/bin/SOMETHING" || fail "Could not set executable bit on binary"
     echo "The installation was successful!"
   ) || (
     rm -rf "$install_path"
@@ -61,4 +61,4 @@ install_direnv() {
   )
 }
 
-install_direnv "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
+install_SOMETHING "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
